name: Build and Publish Container

on:
  # via github UI
  workflow_dispatch:
  push:
    branches: ['*']
    # Publish semver tags as releases.
    tags: ['v*.*.*']
  pull_request:
    branches: ['main']

env:
  HUSKY: 0

jobs:
  build_and_test:
    name: Build and Test library
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: yarn
      - run: yarn test:ci
